### ISSUE TITLE
Error: Could not parse version: line is '// TypeScript Version: 2.7'

### ISSUE THREAD

**Issue by dex4er** [Microsoft/definitelytyped-header-parser#11]
I want to use options

```
// TypeScript Version: 2.7
```

because of 

```js
"esModuleInterop": true
```

in `tsconfig.json` but `npm run lint` shows:

```
Error: Could not parse version: line is '// TypeScript Version: 2.7'
    at Object.parseTypeScriptVersionLine (/Users/dexter/src/js/DefinitelyTyped/node_modules/definitelytyped-header-parser/index.js:177:15)
    at getTypeScriptVersion (/Users/dexter/src/js/DefinitelyTyped/node_modules/dtslint/bin/index.js:125:44)
    at /Users/dexter/src/js/DefinitelyTyped/node_modules/dtslint/bin/index.js:93:28
    at Generator.next (<anonymous>)
    at fulfilled (/Users/dexter/src/js/DefinitelyTyped/node_modules/dtslint/bin/index.js:5:58)
    at <anonymous>
```

**Comment by andy-ms** [comment]
A `// TypeScript Version` sets the *minumum* TypeScript version. We will also test against `typescript@next` in addition to that.

**Comment by UselessPickles** [comment]
Is this a bug that will be fixed? I'm trying to write some dtslint tests involving something that only works as of TS 2.7.1, so I want to ensure that dtslint tests only with 2.7+.

**Comment by andy-ms** [comment]
Should be fixed now.
